### ISSUE TITLE
chore: add a dependabot workflow for the sdk generator github actions

### ISSUE THREAD

**Issue by rhamzeh** [openfga/sdk-generator#214]
The file would be called `.github/dependabot.yaml` and contain:

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
     dependencies:
        patterns:
          - "*"
```
